### PR TITLE
remove iOS platform

### PR DESCRIPTION
**Pull request by lukepighetti**
I noticed that the iOS platform was not in use. This PR deletes the iOS plugin.

### CODE REVIEW

**Comment by alexmercerind** [comment]
I'm currently incapable of maintaining iOS & macOS implementations (though they share more than 90% of the code, same C/C++ [`core`](https://github.com/alexmercerind/dart_vlc/tree/master/core)). More regarding this at #254 & #242.

With that being said, I think Flutter 3 has caused macOS impl. to break again.

Technically speaking, it is possible to use iOS currently as well with just audio & old video playback approach (i.e. sending raw video frame pixel buffers as BGRA/RGBA & rendering using `RawImage` in Flutter itself), but this video playback is difficult for CPU & very similar to how camera plugin works (so I have to decide whether this should be merged or not). For the note, other platforms have been moved to texture registrar APIs, and I'm planning to switch to libvlc 4.0 & render performant video playback.
Since I never worked on macOS or iOS, iOS still doesn't have video support, macOS _has_ video support but that's also not something too great right now. For same reason, _iOS_ CI is missing because I'm not familiar with macOS/iOS development "norms".

**Comment by GroovinChip** [comment]
@alexmercerind I tested @lukepighetti's PR and it works. I think it should be merged, as it unblocks a major issue.

**Comment by alexmercerind** [comment]
Feel free to merge.

Thanks.

**Comment by GroovinChip** [comment]
Oy vey 🤦‍♂️

**Pull request merged**
