### PR TITLE
Updated ffi to 2.0.1

### PR DESCRIPTION
**Pull request by zezo357**

### CODE REVIEW

**Comment by AndreHaueisen** [comment]
Any chance we can merge this PR?

**Comment by Rexios80** [comment]
Since it doesn't look like any actual code changed, we should just be able to do:

```yaml
dependency_overrides:
  ffi: ^2.0.1
```

**Comment by trapeye** [comment]
> Since it doesn't look like any actual code changed, we should just be able to do:
> 
> ```yaml
> dependency_overrides:
>   ffi: ^2.0.1
> ```

But I get this warning
Warning: You are using these overridden dependencies:
! ffi 2.0.1

**Comment by Rexios80** [comment]
Okay... warnings are to let you know there might be a problem, not that there necessarily is one.

**Comment by alexmercerind** [comment]
Hey guys, sorry for being inactive.

I've been occupied with my exams & college.
Maintaining open-source packages requires consistent work & time out of daily life.
Writing C++ & native code is even more tedious. There are a number of issues with this package, both in regard of performance & stability which I would like to fix but couldn't spare my time.

Hardware acceleration is a big concern. Currently, a large load on CPU is made for every video rendered using package:dart_vlc, this is because GPU & GPU backed buffers are not utilized. 

Now, my work is sponsored by [Stream](https://getstream.io/chat/sdk/flutter/?utm_source=alexmercerind_dart&utm_medium=Github_Repo_Content_Ad&utm_content=Developer&utm_campaign=alexmercerind_December2022_FlutterSDK_klmh22).
I can now proceed my work with peace & build the best-ever video playback solution for Flutter Desktop.

Thanks!

**Pull request merged**
