### PR TITLE
Linux: Use texture registrar APIs for video playback

### PR DESCRIPTION
**Pull request by alexmercerind**
**This PR adds:**

- Texture based performant video playback on Linux. https://github.com/flutter/engine/pull/24916
- Progress on #107.

Screenshot_20210926_151237

### CODE REVIEW

**Review by krjw-eyev — COMMENTED** [review]
LGTM

I know it is a pain but I think we should introduce tests at some point.

**Comment by alexmercerind** [comment]
@krjw-eyev so I wanted to say something important, 

so this PR will add texture support for Linux aswell after Windows & macOS aswell.

Current iOS video playback isn't texture based & it won't work unless we again use NativePorts (which is really bad for performance). I don't have a macOS or iOS running machine, I want you to:
- Test if macOS is still working (as I just merged its texture migration PR).
- Implement texture based video playback for iOS aswell, I believe it will be a lot lot same as macOS again.

Thanks a lot.
Please let me know, if you'd wanna do it before this PR gets merged or after this.

**Comment by krjw-eyev** [comment]
I will test on macOS in a second. I don't know if I can implement this in iOS but I will have a look!

**Comment by krjw-eyev** [comment]
macOS works I would say. It is very smooth!

**Pull request merged**
