### PR TITLE
Fix autoStart (#64)

### PR DESCRIPTION
**Pull request by t1ooo**

### CODE REVIEW

**Comment by alexmercerind** [comment]
@t1ooo this is not how it would be done. Did you confirm the fix in your this PR? 
It was one of the reasons why I didn't do it in the first place.

**Comment by t1ooo** [comment]
Yes, autoStart works correctly after fix. But I have no tests ¯\_(ツ)_/¯
I found two commits related to this 200ea7ae1c696f9df72821f0ac914dc861194e1b daf3bcdafb1f0d4b859d5d9ec38b41b38a09643a. Is this how it should be fixed?

**Comment by alexmercerind** [comment]
@t1ooo I myself don't have any idea. I'm just confused between what things to target. I will look once I switch to `flutter:TextureRegistrar` for Windows.

**Comment by alexmercerind** [comment]
@t1ooo I've published fix for this in 0.1.2. Reverted this PR.

**Pull request merged**
